PackageIdentifier: Roethlar.Blit
PackageVersion: 0.1.3
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/roethlar/Blit/releases/download/v0.1.3/blit-x86_64-pc-windows-msvc.zip
  InstallerSha256: 11590DF1AFF250C1FC94A210AC1C356F00E5A4FF8C36CF538C3CCF90A601EDE1
  NestedInstallerFiles:
  - RelativeFilePath: blit-x86_64-pc-windows-msvc/blit.exe
    PortableCommandAlias: blit
  - RelativeFilePath: blit-x86_64-pc-windows-msvc/blit-daemon.exe
    PortableCommandAlias: blit-daemon
ManifestType: installer
ManifestVersion: 1.6.0
